### ISSUE TITLE
frequency problem perhaps

### ISSUE THREAD

**Issue by ghost** [mitsuman/mdx2wav#1]
I tried this library and noticed that no matter which frequency I select, the output sounds the same always. It sounds like 22050Hz all the time. For the comparison I used BouKichi library and the difference is quite noticeable.

**Comment by mitsuman** [comment]
Thanks for trying!
Maybe you treat output pcm as monoral.
Could you tell me command line and mdx file you tried ?

**Comment by ghost** [comment]
Hello,

ftp://ftp.modland.com/pub/modules/MDX/After%20Burner/ab2-bfd.mdx

Try that, there is a .pdx file in the same folder. 

i didn't use the command line tool, just used it as a library. I tried all the options :(

Additional links:
https://www.dropbox.com/s/m469l6fb375x0bo/ab2-bfd.mdx?dl=0
https://www.dropbox.com/s/9kz43ngicx3444e/ab2.pdx?dl=0

**Comment by mitsuman** [comment]
oh, what a great ftp server...

I tried 
./mdx2wav ab2-bfd.mdx > ab2-bfd.44100hz.pcm
./mdx2wav -r 22050 ab2-bfd.mdx > ab2-bfd.22050hz.pcm
and got expected results that's 16bit little endian stereo 44100hz pcm and 22050hz pcm.

> i didn't use the command line tool, just used it as a library.

mdx2wav is a command line tool, NOT a library.
you talk about MXDRVg ??
If so please read src/mdx2wav.cpp to confirm how to use MXDRVg.

**Comment by droidmjt** [comment]
i just tried with mdx2wav and no matter what frequency i select, it sounds bad, the quality sounds like 22050 all the time. If you can, try with boukichi's library and you'll hear the difference

**Comment by droidmjt** [comment]
I'll post some samples soon so you can hear it

**Comment by ghost** [comment]
https://www.dropbox.com/s/4zmw0q143ztwiq5/ab2-bfd_boukichi.wav?dl=0

there, 30 second clip using stereo + 44100hz 16bit with boukichi library

**Comment by ghost** [comment]
yes i know the mdx2wav is not a library but i used the same library that the mdx2wav uses and i was thinking if you would be able to solve that frequency related problem. Sorry for a small confusion.

**Comment by ghost** [comment]
if you don't have time/interest in trying to fix the gamdx lib, its ok :)
